apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sblocklatesttag
  annotations:
    description: >-
      Prevents the use of 'latest' or unspecified image tags in container
      deployments to ensure version traceability and reproducibility.
spec:
  crd:
    spec:
      names:
        kind: K8sBlockLatestTag
      validation:
        openAPIV3Schema:
          type: object
          properties:
            exemptImages:
              description: Any container that uses an image that matches an entry in this list will be excluded from enforcement. Prefix-matching can be signified with `*`. For example, `my-image-*` would match all images that begin with `my-image-`.
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sblocklatesttag

        import future.keywords.in

        violation[{"msg": msg}] {
          container := input_containers[_]
          not is_exempt(container.image)
          has_latest_tag(container)
          msg := sprintf("container <%v> uses an unversioned or 'latest' image tag <%v>, which is not allowed", [container.name, container.image])
        }

        input_containers[c] {
          c := input.review.object.spec.containers[_]
        }

        input_containers[c] {
          c := input.review.object.spec.initContainers[_]
        }

        input_containers[c] {
          c := input.review.object.spec.ephemeralContainers[_]
        }

        has_latest_tag(container) {
          endswith(container.image, ":latest")
        }

        has_latest_tag(container) {
          not contains(container.image, ":")
        }

        has_latest_tag(container) {
          endswith(container.image, ":")
        }

        is_exempt(image) {
          exempt_image := object.get(input, "parameters", {}).exemptImages[_]
          _matches_exempt(image, exempt_image)
        }

        _matches_exempt(image, exempt_image) {
          not endswith(exempt_image, "*")
          exempt_image == image
        }

        _matches_exempt(image, exempt_image) {
          endswith(exempt_image, "*")
          prefix := trim_suffix(exempt_image, "*")
          startswith(image, prefix)
        }
