apiVersion: v1
kind: ConfigMap
metadata:
  name: applyforus-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "applyforus.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
